
help:
	@echo '-----------------------------------------'
	@echo 'make all            	build all targets'
#	@echo make clean	   	clean all targets
	@echo 'make help 	   	this help info'
#	@echo make -C target clean 	clean specific target
	@echo 'make -C target all 	build specific target'
	@echo '-----------------------------------------'

include custom.mk
all:${TARGETS}

clean: clear

.PHONY:all ${TARGETS} 

