
all:
	gcc -o plock-test plock-test.c process-lock.c -I./ -lpthread
	gcc -o plock-test2 plock-test2.c process-lock.c -I./ -lpthread
clean:
	rm -rf plock-test
	rm -rf plock-test2
	rm -rf process-lock.o
