
	 # what does lrt mean ? I dont know, but add it can compile correct! wow
all:
	gcc -o mqcreate1 -lrt mqcreate1.c
	gcc -o mqunlink -lrt mqunlink.c
	gcc -o mqgetattr -lrt mqgetattr.c
	gcc -o mqcreate -lrt mqcreate.c
	gcc -o mqsend -lrt mqsend.c
	gcc -o mqrecv -lrt mqrecv.c
	gcc -o select-mq -lrt select-mq.c
	gcc -o pthread-mq -lrt pthread-mq.c
clean:
	rm -rf mqcreate1 mqunlink mqgetattr mqcreate mqsend mqrecv select-mq pthread-mq
