



SRCS=classihello.c
OBJS=classihello.o
TARGETS=classihello

all: ${TARGETS}

classihello: classihello.c
	gcc -Wall -g -o classihello classihello.c

clean:
	rm -f ${TARGETS} ${OBJS}
.PHONY: ${TARGETS} ${OBJS} clean
