

all:
	gcc -o exhange_2_varibles exchange_2_varibles.c
	gcc -o exhange_2_varibles_2 exchange_2_varibles_2.c
	gcc -o exhange_3_varibles exchange_3_varibles.c
clean:
	rm -rf exhange_2_varibles exhange_2_varibles_2 exhange_3_varibles
